### ISSUE TITLE
Create distribution charts

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#497]

**Comment by connor-makowski** [comment]
These charts should include both bar and line charts as well as cover both PDF and CDF with different bucket sizes. I am all ears for a UI/UX proposal here.

**Comment by katherineyli** [comment]
@connor-makowski @mrkwanzaa Any suggestions for improvement? Also, I was wondering if it is possible to make all of the bars/line segments the same color, as that is usually standard for PDF/CDF charts.

**Comment by mrkwanzaa** [comment]
This looks really good, and they're working great! I have a few small notes but overall excellent job. 

- Grouping doesn't work after you get rid of the default grouping. Just adding entries for them in `chartMaxGroupings` found in `utils/enums.js` should fix this.
- The default number of buckets probably shouldn't be one, since you'd never want one bucket. Maybe update this to default at 10 and set 2 as the minimum.
- The buckets slider label covers the toolbar, or goes above the chart if it's hidden. I'd move this down and maybe add a text label to indicate to users what it does.

As far as the coloring goes, you can specify the `coloring` parameter when you base the data to the BaseChart component, or do something more custom (eg add a colorSame prop to BaseChart) if you feel that's cleaner from a code side.

**Comment by connor-makowski** [comment]
Looking good so far. 

Regarding the colors, lets think about that a bit more.

I think we will need a new always available grouping structure (like None - which is really just one big group) for each element - meaning each element is its own group. For naming, we might have something like `All` which is the current `None` and `None` which is actually individual elements. 

This could be useful for all charts considering we now have filters per chart and can filter down to very granular data.

**Comment by connor-makowski** [comment]
@mrkwanzaa I could see a number of potential rammifications here, but if we default no grouping selection to `All` then I think we could avoid any breaking changes. This however represents a hardcoded element. Do you see any other potential for breaking changes here?

**Comment by katherineyli** [comment]
@connor-makowski @mrkwanzaa I've made a lot of adjustments to the distribution charts; let me know if you have any additional thoughts! Thanks.

**Comment by connor-makowski** [comment]
Those are coming along really well!!! It is making me rethink some of our future charting developments. The only thing I see left for this issue is figuring out how to better represent the buckets from a UI perspective and where to place the num buckets slider.

**Comment by mrkwanzaa** [comment]
I'm also a big fan of how these are turning out. The only obvious issues I'm seeing is that if you subgroup the legend overlaps with the buckets slider, and sometime the pdf/cdf dropdown starts scrolling (I'm guessing this is related to #502 ).

**Comment by katherineyli** [comment]
Moved slider to bottom of chart: [fe56d6a](https://github.com/MIT-CAVE/cave_static/commit/fe56d6aa186c48e4b4cbd1f4d81e792d13c10313)

**Comment by connor-makowski** [comment]
Closing after merging #519
