### ISSUE TITLE
Redo how sum/avg/min/max in the charts

### ISSUE THREAD

**Issue by connor-makowski** [MIT-CAVE/cave_static#500]
Lets think of a better way to do these. Especially for averages.

**Comment by connor-makowski** [comment]
I think we should also add a count feature

**Comment by mrkwanzaa** [comment]
I believe the current issue with how aggregation works is that the individual grouped output objects aren't always something that makes sense to aggregate. For example in one internal app, one object is technically a product type at a time at a location in a storage section with a transportation modality. With the additional fact that the base object can change between different statistics it becomes really unclear to both users and API developers what they are summing averaging etc. Even when these functions could be useful, they aren't used due to how unclear this is.

The solution that I'm considering is the ability to specify a grouping level to aggregate over. For example, you could average over weeks, look only at the max lead times per dc, or count the number of products at every store. This would greatly clarify what level we're at, without removing any functionality as users and API designers can just aggregate without specifying a group to get the current behavior

**Comment by mrkwanzaa** [comment]
Per our discussion, we'll be moving this to 3.0. as part of a larger overhaul of these structures
